### ISSUE TITLE
Could Escape fit on a floppy?

### ISSUE THREAD

**Issue by informer2016** [Nils-TUD/Escape#11]
Even today the floppies are still being used, for example - as virtual floppies inside the coreboot open source BIOS. Just imagine: your wonderful OS could be a part of someone's BIOS build! _(for coreboot supported motherboard, maybe you have or could get one - see https://www.coreboot.org/Supported_Motherboards )_

If you already have a coreboot-supported motherboard, or a real chance to get one, - wouldn't it be cool to be able to launch your own OS straight from the BIOS chip? ;) With one simple command its possible to add any floppy to coreboot BIOS build - and then you see it as a boot entry! Multiple floppies could be added this way _(as long as you have enough space left inside the BIOS flash chip, luckily LZMA compression could be used for the stored floppies to reduce their occupied size)_

**Comment by adamc295** [comment]
But then you'd run into space issues.

With all this stuff in an OS, you probably would run into space issues, and would need to strip it of any cool things (like the GUI). 

I'm not saying it's _impossible_, but I'm just saying it would be hard.

**Comment by informer2016** [comment]
@adamc295 Maybe it could be more realistic with 2.88MB double size floppy _(they are also supported by coreboot/SeaBIOS)_ instead of 1.44MB - to preserve as much cool things as possible :wink:  But sadly there aren't many people who are interested both in coreboot BIOS and hobby OS, so I can understand you
