### ISSUE TITLE
unable to reach to desktop.

### ISSUE THREAD

**Issue by Manish-Kala-Jaat** [Nils-TUD/Escape#12]
I am unable to launch the desktop to reach to the GUI mode.
after logging in I just typed desktop but it shows error:
terminate called after throwing an instance of 'N3esc13default_errorE'
 what(): Env-var WINMNG not set
help me to lauch the gui mode.

![Screenshot (5630)](https://user-images.githubusercontent.com/49841018/57455990-15e6a080-728a-11e9-9003-c27feff74f20.png)

**Comment by Nils-TUD** [comment]
You can start a GUI with ctrl+G. Similarly, you can create new text UIs with ctrl+T.

**Comment by Manish-Kala-Jaat** [comment]
What is the login details

गुरु, 9 मई 2019, 6:43 pm को Nils Asmussen <notifications@github.com> ने
लिखा:

**Comment by Nils-TUD** [comment]
The same as for the text UIs (see your screenshot "Hint: use ...").

**Comment by Manish-Kala-Jaat** [comment]
Thanks a lot

गुरु, 9 मई 2019, 7:04 pm को Nils Asmussen <notifications@github.com> ने
लिखा:

**Comment by Manish-Kala-Jaat** [comment]
Escape os crashes in virtual box.
It crashes just after starting it.

**Comment by Nils-TUD** [comment]
I've just played around with that a bit. Newer virtualbox versions seem to disable long mode  (64-bit mode) if you don't select a 64-bit OS as the guest. Therefore, virtualbox stops Escape as soon as it tries to switch to long mode. So, in virtualbox, in general -> basic -> "type" and "version" you need to select "Other" and "Other/Unknown 64-bit". Then it works for me.
